require('./common')
require('./images/logo-banner.svg')
require('./images/BCSans-Bold.woff')
require('./images/BCSans-Bold.woff2')
require('./images/BCSans-BoldItalic.woff')
require('./images/BCSans-BoldItalic.woff2')
require('./images/BCSans-Italic.woff')
require('./images/BCSans-Italic.woff2')
require('./images/BCSans-Regular.woff')
require('./images/BCSans-Regular.woff2')
require('./images/radar_legend.png')
require('./analytics.js')

const Factory = require('./util/factory')

Factory().build()
